Add controllers
worthless1/java-shareit pull request #1
Opened 2023-07-30 05:01 UTC by worthless1

Add controllers

2023-07-30 11:16 UTC, db-exp requested changes

2023-07-30 11:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    ItemMapper INSTANCE = Mappers.getMapper(ItemMapper.class);
а зачем? можно просто сделать методы статическими)

2023-07-30 11:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
совет  - в сервисах хорошо использовать Transactional анноатцию, без параметров она и на чтение и на запись, а с параметром (readOnly=true) - на чтение

2023-07-30 11:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +        User user = userStorage.findUserById(userId);
проще Onptional.ofNullable().orElseThrow

2023-07-30 11:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
лучше использовать "чужие" сервисы, а не репозитории - так ты уменьшаешь связность кода

2023-07-30 11:16 UTC, db-exp commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +            throw new NotFoundException("User with ID " + userId + " does not own the item with ID " + itemId);
лучше что-то типа ForbiddenException

2023-07-31 01:59 UTC, worthless1 commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    ItemMapper INSTANCE = Mappers.getMapper(ItemMapper.class);
Это же интерфейс, библиотека сама сгенерует методы маппера. Если я сделаю их статическими, тогда мне придется добавить тело методам

2023-07-31 02:03 UTC, worthless1 commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
Разве в этом сервисе есть методы, которые нуждаются в @Transactional?

2023-07-31 02:09 UTC, worthless1 commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImpl.java
> +    private final UserService userService;
Я же и использую тут чужой сервис - UserService

2023-07-31 12:32 UTC, db-exp approved these changes

2023-07-31 12:32 UTC, db-exp commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +public class UserServiceImpl implements UserService {
Ну смотри - чтение из базы с Transactional дает гарантию получения предсказуемых данных - тут get методы, создание, в принципе здесь не требует транзакции потому что в одну операцию все проиходит

2023-08-13 17:14 UTC, merged